# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Aerohive Device Tracker
version: "1.0.1"
slug: aerohive_tracker
description: Track WiFi devices accross multiple APs of an Aerohive mesh network.  Only wireless devices are tracked.
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
options:
  aerohive_password: ""
  aerohive_host: ""
  aerohive_username: "admin"
  mqtt_host: "localhost"
  mqtt_port: "1883"
  mqtt_username: "" 
  mqtt_password: ""
  mqtt_topic: "device_tracker/aerohive"
  preinit_macs: ""
  ignore_regex_mac: ""
  ignore_regex_ip: ""
  ignore_regex_name: ""
schema:
  aerohive_password: 'str'
  aerohive_host: 'str'
  aerohive_username: 'str'
  mqtt_host: 'str'
  mqtt_port: 'int'
  mqtt_username: 'str'
  mqtt_password: 'str'
  mqtt_topic: 'str'
  preinit_macs: 'str'
  ignore_regex_mac: 'str'
  ignore_regex_ip: 'str'
  ignore_regex_name: 'str'
